create extension if not exists pgcrypto;

create table if not exists public.tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.tenant_memberships (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('owner','admin','trader','viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(tenant_id,user_id)
);

create index if not exists tenant_memberships_user_idx on public.tenant_memberships(user_id);
create index if not exists tenant_memberships_tenant_idx on public.tenant_memberships(tenant_id);

create table if not exists public.connector_credentials (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  label text not null,
  source text not null check (source in ('mt5','profit','generic')),
  key_hash text not null unique,
  last4 text not null,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz
);

create index if not exists connector_credentials_tenant_idx on public.connector_credentials(tenant_id);

create table if not exists public.autotrade_configs (
  tenant_id uuid primary key references public.tenants(id) on delete cascade,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.execution_intents (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  source text not null,
  symbol text not null,
  timeframe text not null,
  side text not null check (side in ('BUY','SELL')),
  mode text not null check (mode in ('paper','live')),
  entry numeric not null,
  stop_loss numeric,
  take_profit numeric,
  confidence integer not null,
  score integer not null,
  status text not null check (status in ('PENDING','CLAIMED','EXECUTED','REJECTED','EXPIRED')),
  note text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists execution_intents_tenant_time_idx on public.execution_intents(tenant_id,created_at desc);

create table if not exists public.tenant_audit_log (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  event text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.is_tenant_member(target_tenant uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.tenant_memberships tm
    where tm.tenant_id=target_tenant
      and tm.user_id=auth.uid()
      and tm.active=true
  );
$$;

create or replace function public.is_tenant_admin(target_tenant uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.tenant_memberships tm
    where tm.tenant_id=target_tenant
      and tm.user_id=auth.uid()
      and tm.active=true
      and tm.role in ('owner','admin')
  );
$$;

alter table public.tenants enable row level security;
alter table public.profiles enable row level security;
alter table public.tenant_memberships enable row level security;
alter table public.connector_credentials enable row level security;
alter table public.autotrade_configs enable row level security;
alter table public.execution_intents enable row level security;
alter table public.tenant_audit_log enable row level security;

drop policy if exists tenants_read_members on public.tenants;
create policy tenants_read_members on public.tenants
for select to authenticated
using (public.is_tenant_member(id));

drop policy if exists profiles_read_same_tenant on public.profiles;
create policy profiles_read_same_tenant on public.profiles
for select to authenticated
using (
  id=auth.uid() or exists(
    select 1
    from public.tenant_memberships mine
    join public.tenant_memberships theirs on theirs.tenant_id=mine.tenant_id
    where mine.user_id=auth.uid() and mine.active=true and theirs.user_id=profiles.id and theirs.active=true
  )
);

drop policy if exists memberships_read_same_tenant on public.tenant_memberships;
create policy memberships_read_same_tenant on public.tenant_memberships
for select to authenticated
using (public.is_tenant_member(tenant_id));

drop policy if exists connectors_admin_only on public.connector_credentials;
create policy connectors_admin_only on public.connector_credentials
for select to authenticated
using (public.is_tenant_admin(tenant_id));

drop policy if exists autotrade_read_member on public.autotrade_configs;
create policy autotrade_read_member on public.autotrade_configs
for select to authenticated
using (public.is_tenant_member(tenant_id));

drop policy if exists intents_read_member on public.execution_intents;
create policy intents_read_member on public.execution_intents
for select to authenticated
using (public.is_tenant_member(tenant_id));

drop policy if exists audit_read_admin on public.tenant_audit_log;
create policy audit_read_admin on public.tenant_audit_log
for select to authenticated
using (public.is_tenant_admin(tenant_id));

create or replace function public.handle_new_user_profile()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,display_name)
  values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();
